name: Java Spring Boot CI/CD Pipeline

on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-server-ip >> ~/.ssh/known_hosts

      - name: Login to server
        run: |
            ssh -o StrictHostKeyChecking=no user@your-server-ip "echo 'Logged in successfully!'"