name: Java Spring Boot CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Login to server
        run:  |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  $S_USER@$S_HOST
          ll