name: Build and Test Spring Boot Application with Java 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build and test with Maven
        run: ./mvnw  clean install -DskipTests=false

      - name: Run tests
        run: ./mvnw  test
