name: Build and Test Spring Boot Application with Java 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'         # Java version to install
          distribution: 'temurin'

      - name: Build and test with Maven
        run: ./mvnw  clean install -DskipTests=false

      - name: Run tests
        run: ./mvnw  test
